repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: check-added-large-files
        -   id: check-yaml
            exclude: chart/templates
        -   id: debug-statements
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-ast
        -   id: check-builtin-literals
        -   id: detect-private-key
        -   id: mixed-line-ending
        -   id: no-commit-to-branch

    # finding and removing unused import statements
    -   repo: https://github.com/jendrikseipp/vulture
        rev: v2.6
        hooks:
        -   id: vulture

    # format and sort Python imports
    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        -   id: isort

    # format Python code with black
    -   repo: https://github.com/psf/black
        rev: 22.10.0
        hooks:
        -   id: black

    # code style checker with flake8
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 5.0.4
        hooks:
        -   id: flake8

    # static type checking with mypy
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.982
        hooks:
        -   id: mypy

    # interrogate checks your code base for missing docstrings.
    -   repo: https://github.com/econchick/interrogate
        rev: 1.5.0
        hooks:
        -   id: interrogate

    # conventional commit checking with commitizen
    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.35.0
        hooks:
        -   id: commitizen
            stages: [commit-msg]
