version: '3.7'

networks:
  app-net:

services:
  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    image: fastapi-boilerplate_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-net
